 - name: install tomcat
   yum:
    name: tomcat
    state: latest
 - name: start service
   service:
    name: tomcat
    state: started
 - name: copy files
   copy:
    src: "{{src_path}}"
    dest: "{{dest_path}}"
   notify: restart tomcat
