  - name : install tomcat
    yum:
     name: tomcat
     state: latest
  - name: start  service
    service:
     name: tomcat
     state: started
  - name: copy Calendar.war file to webapps
    copy:
     src: Calendar.war
     dest: "{{ dest_path }}"
    notify: restart tomcat
